server:
  port: 8081

spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # routes: =====================================
        - id: user-channel
          uri: http://127.0.0.1:8081
          order: 8000
          predicates:
          - Path=/user/**
          filters:
          - name: Demo
            args:
              id: 2
              val: 2
        - id: g
          uri: https://github.com/roboslyq/
          order: 8000
          predicates:
          - Path=/g/**
          filters:
          - name: Demo
            args:
              id: 1
              val: 1
