spring:
  datasource:
    primary:
      username: root
      password: a(A
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 如果未使用druid,下面参数是jdbc-url。如果已经使用druid,下面参数是url
      url: jdbc:mysql://:3306/test_primary?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,log4j
      initialSize: 0
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 30000
      minIdle: 2
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 6000
      validationQuery: SELECT 1 FROM DUAL

    secondary:
      username: root
      password: a(A
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 如果未使用druid,下面参数是jdbc-url。如果已经使用druid,下面参数是url
      url: jdbc:mysql://127.0.0.1:3306/test_secondary?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,log4j
      initialSize: 0
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 30000
      minIdle: 2
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 6000
      validationQuery: SELECT 1 FROM DUAL

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
    show-sql: true