spring:
  datasource:
    webflux:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://47.93.201.88:3306/spring_learn?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: test_user
      password: 1q2w3e4r(A